In [96]:
import pandas as pd
import itertools as iter

In [97]:
# Load data from csv
df_2009 = pd.read_csv('data/kcmo/pd/kcpd2009.csv')
df_2010 = pd.read_csv('data/kcmo/pd/kcpd2010.csv')
df_2011 = pd.read_csv('data/kcmo/pd/kcpd2011.csv')
df_2012 = pd.read_csv('data/kcmo/pd/kcpd2012.csv')
df_2013 = pd.read_csv('data/kcmo/pd/kcpd2013.csv')
df_2014 = pd.read_csv('data/kcmo/pd/kcpd2014.csv')
df_2015 = pd.read_csv('data/kcmo/pd/kcpd2015.csv')
df_2016 = pd.read_csv('data/kcmo/pd/kcpd2016.csv')
df_2017 = pd.read_csv('data/kcmo/pd/kcpd2017.csv')
df_2018 = pd.read_csv('data/kcmo/pd/kcpd2018.csv')

In [98]:
# Get column names
columns = [df_2009.columns, df_2010.columns, df_2011.columns, df_2012.columns, df_2013.columns, df_2014.columns, df_2015.columns, 
            df_2016.columns, df_2017.columns, df_2018.columns]
columns = list(map(list, iter.zip_longest(*columns, fillvalue='-')))
pd.DataFrame(columns, columns=['2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018'])

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Report_No,Report_No,Report_No,Report_No,Report_No,Report_No,Report_No,Report_No,Report_No,Report_No
1,Reported_Date,Reported_Date,Reported_Date,Reported_Date,Reported_Date,Reported_Date,Reported_Date,Reported_Date,Reported_Date,Reported_Date
2,Reported Time,Reported Time,Reported Time,Reported Time,Reported Time,Reported Time,Reported Time,Reported_Time,Reported_Time,Reported_Time
3,From_Date,From_Date,From_Date,From_Date,From_Date,From_Date,From_Date,From_Date,From_Date,From_Date
4,From Time,From Time,From Time,From Time,From Time,From Time,From Time,From_Time,From_Time,From_Time
5,To_Date,To_Date,To_Date,To_Date,To_Date,To_Date,To_Date,To_Date,To_Date,To_Date
6,To_Time,To Time,To Time,To Time,To Time,To Time,To Time,To_Time,To_Time,To_Time
7,Offense,Offense,Offense,Offense,Offense,Offense,Offense,Offense,Offense,Offense
8,IBRS,IBRS,IBRS,IBRS,IBRS,IBRS,IBRS,IBRS,IBRS,IBRS
9,Description,Description,Description,Description,Description,Description,Description,Description,Description,Description
10,Beat,Beat,Beat,Beat,Beat,Beat,Beat,Beat,Beat,Beat
11,Address,Address,Address,Address,Zip Code,Address,Address,Address,Address,Address
12,City,Zip Code,City,City,Rep_Dist,City,City,City,City,City
13,Zip Code,City,Zip Code,Zip Code,Area,Zip Code,Zip Code,Zip Code,Zip Code,Zip Code
14,Rep_Dist,Rep_Dist,Rep_Dist,Rep_Dist,DVFlag,Rep_Dist,Rep_Dist,Rep_Dist,Rep_Dist,Rep_Dist
15,Area,Area,Area,Area,Invl_No,Area,Area,Area,Area,Area
16,DVFlag,DVFlag,DVFlag,DVFlag,Involvement,DVFlag,DVFlag,DVFlag,DVFlag,DVFlag
17,Invl_No,Invl_No,Invl_No,Invl_No,Race,Invl_No,Invl_No,Invl_No,Invl_No,Invl_No
18,Involvement,Involvement,Involvement,Involvement,Sex,Involvement,Involvement,Involvement,Involvement,Involvement
19,Race,Race,Race,Race,Age,Race,Race,Race,Race,Race
20,Sex,Sex,Sex,Sex,Firearm,Sex,Sex,Sex,Sex,Sex
21,Age,Age,Age,Age,Location 1,Age,Age,Age,Age,Age
22,Location 1,Location 1,Location 1,Location 1,-,Location 1,Firearm Used Flag,Firearm Used Flag,Firearm Used Flag,Firearm Used Flag
23,Firearm Used Flag,Firearm Used Flag,Firearm Used Flag,Firearm Used Flag,-,Firearm Used Flag,Latitude,Latitude,Location,Location
24,-,-,-,-,-,-,Longitude,Longitude,-,-
25,-,-,-,-,-,-,Location 1,Location 1,-,-

* Columns names doesn't match - To Time, From Time, Location, Firearm Used Flag
  * Rename columns using dataframe.rename
* Address, City missing in 2013
  * Drop from other years
* Extra columns - Latitude, Longitude in 2015, 2016
  * Drop extra columns in 2015, 2016
* Columns Firearm, Location swapped in 2009-2014 and 2015-2018 
* Columns City, Zip Code swapped in 2010

**Use a common column name list to handle ordering, missing or extra columns**

In [99]:
# Common column list
cols = ['Report_No', 'Reported_Date', 'Reported Time', 'From_Date', 'From Time', 'To_Date', 
        'To_Time', 'Offense', 'IBRS', 'Description', 'Beat', 'Zip Code', 
        'Rep_Dist', 'Area', 'DVFlag', 'Invl_No', 'Involvement', 'Race', 'Sex', 'Age', 
        'Location', 'Firearm Used Flag', ]

In [100]:
df_2009 = df_2009.rename(columns={'Location 1':'Location', 'Firearm Used Flag  ':'Firearm Used Flag'})
df_2010 = df_2010.rename(columns={'To Time':'To_Time', 'Location 1':'Location', 'Firearm Used Flag  ':'Firearm Used Flag'})
df_2011 = df_2011.rename(columns={'To Time':'To_Time', 'Location 1':'Location', 'Firearm Used Flag  ':'Firearm Used Flag'})
df_2012 = df_2012.rename(columns={'To Time':'To_Time', 'Location 1':'Location', 'Firearm Used Flag  ':'Firearm Used Flag'})
df_2013 = df_2013.rename(columns={'To Time':'To_Time', 'Location 1':'Location', 'Firearm':'Firearm Used Flag'})
df_2014 = df_2014.rename(columns={'To Time':'To_Time', 'Location 1':'Location', 'Firearm Used Flag  ':'Firearm Used Flag'})
df_2015 = df_2015.rename(columns={'To Time':'To_Time', 'Location 1':'Location'})
df_2016 = df_2016.rename(columns={'Reported_Time':'Reported Time', 'From_Time':'From Time', 'Location 1':'Location'})
df_2017 = df_2017.rename(columns={'Reported_Time':'Reported Time', 'From_Time':'From Time'})
df_2018 = df_2018.rename(columns={'Reported_Time':'Reported Time', 'From_Time':'From Time'})

In [106]:
df_all = pd.concat([df_2009[cols], df_2010[cols], df_2011[cols], df_2012[cols], df_2013[cols], df_2014[cols], 
           df_2015[cols], df_2016[cols], df_2017[cols], df_2018[cols]])

In [108]:
df_all.to_csv('kcpd_all.csv', index=False)

In [105]:
df_all.isnull().sum()

Report_No                 0
Reported_Date             0
Reported Time             0
From_Date              1835
From Time              2753
To_Date              742465
To_Time              718972
Offense                   0
IBRS                  10264
Description               0
Beat                   3195
Zip Code              22893
Rep_Dist               4552
Area                   4579
DVFlag                    0
Invl_No                   0
Involvement               0
Race                 161563
Sex                  161563
Age                  535741
Location                637
Firearm Used Flag         0
dtype: int64